{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "netris-operator.fullname" . }}-manager-role'
rules:
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - bgpconfigurations
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - bgppeers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - ippools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocationmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocationmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocationmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocations/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - allocations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgpmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgpmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgpmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgps/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - bgps/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllermeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllermeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllermeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllers/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - controllers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbs/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - l4lbs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - linkmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - linkmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - linkmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - links
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - links/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - links/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - natmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - natmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - natmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - nats
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - nats/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - nats/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sitemeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sitemeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sitemeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sites
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sites/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - sites/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgatemeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgatemeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgatemeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgates/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - softgates/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnetmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnetmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnetmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnets/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - subnets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switches
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switches/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switches/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switchmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switchmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - switchmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnetmeta
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnetmeta/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnetmeta/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnets/finalizers
    verbs:
      - update
  - apiGroups:
      - k8s.netris.ai
    resources:
      - vnets/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "netris-operator.fullname" . }}-manager-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "netris-operator.fullname" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "netris-operator.serviceAccountName" . }}'
    namespace: '{{ include "netris-operator.namespace" . }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ include "netris-operator.fullname" . }}-leader-election-role'
  namespace: '{{ include "netris-operator.namespace" . }}'
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "netris-operator.fullname" . }}-leader-election-rolebinding'
  namespace: '{{ include "netris-operator.namespace" . }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "netris-operator.fullname" . }}-leader-election-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "netris-operator.serviceAccountName" . }}'
    namespace: '{{ include "netris-operator.namespace" . }}'
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "netris-operator.fullname" . }}-proxy-role'
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "netris-operator.fullname" . }}-proxy-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "netris-operator.fullname" . }}-proxy-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "netris-operator.serviceAccountName" . }}'
    namespace: '{{ include "netris-operator.namespace" . }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "netris-operator.fullname" . }}-metrics-reader'
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
