# permissions for end users to edit allocationmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allocationmeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta/status
  verbs:
  - get
