# permissions for end users to view allocationmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allocationmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta/status
  verbs:
  - get
