apiVersion: v1
kind: Service
metadata:
  labels:
    netris-operator: controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    netris-operator: controller-manager
