# permissions for end users to view bgps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgp-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgps/status
  verbs:
  - get
