# permissions for end users to edit bgpmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgpmeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgpmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgpmeta/status
  verbs:
  - get
