# permissions for end users to view bgpmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgpmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgpmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - bgpmeta/status
  verbs:
  - get
