# permissions for end users to edit controllermeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllermeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllermeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllermeta/status
  verbs:
  - get
