# permissions for end users to view controllermeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllermeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllermeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllermeta/status
  verbs:
  - get
