# permissions for end users to edit controllers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - controllers/status
  verbs:
  - get
