# permissions for end users to edit ebgps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebgp-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - ebgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - ebgps/status
  verbs:
  - get
