# permissions for end users to view ebgpmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebgpmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - ebgpmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - ebgpmeta/status
  verbs:
  - get
