# permissions for end users to view inventoryprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventoryprofile-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - inventoryprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - inventoryprofiles/status
  verbs:
  - get
