# permissions for end users to view inventoryprofilemeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventoryprofilemeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - inventoryprofilemeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - inventoryprofilemeta/status
  verbs:
  - get
