# permissions for end users to view l4lbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: l4lb-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - l4lbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - l4lbs/status
  verbs:
  - get
