# permissions for end users to edit linkmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkmeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - linkmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - linkmeta/status
  verbs:
  - get
