# permissions for end users to view linkmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - linkmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - linkmeta/status
  verbs:
  - get
