# permissions for end users to edit natmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: natmeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - natmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - natmeta/status
  verbs:
  - get
