---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - bgpconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - bgppeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta
  - allocations
  - bgpmeta
  - bgps
  - controllermeta
  - controllers
  - inventoryprofilemeta
  - inventoryprofiles
  - l4lbmeta
  - l4lbs
  - linkmeta
  - links
  - natmeta
  - nats
  - sitemeta
  - sites
  - softgatemeta
  - softgates
  - subnetmeta
  - subnets
  - switches
  - switchmeta
  - vnetmeta
  - vnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta/finalizers
  - allocations/finalizers
  - bgpmeta/finalizers
  - bgps/finalizers
  - controllermeta/finalizers
  - controllers/finalizers
  - inventoryprofilemeta/finalizers
  - inventoryprofiles/finalizers
  - l4lbmeta/finalizers
  - l4lbs/finalizers
  - linkmeta/finalizers
  - links/finalizers
  - natmeta/finalizers
  - nats/finalizers
  - sitemeta/finalizers
  - sites/finalizers
  - softgatemeta/finalizers
  - softgates/finalizers
  - subnetmeta/finalizers
  - subnets/finalizers
  - switches/finalizers
  - switchmeta/finalizers
  - vnetmeta/finalizers
  - vnets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.netris.ai
  resources:
  - allocationmeta/status
  - allocations/status
  - bgpmeta/status
  - bgps/status
  - controllermeta/status
  - controllers/status
  - inventoryprofilemeta/status
  - inventoryprofiles/status
  - l4lbmeta/status
  - l4lbs/status
  - linkmeta/status
  - links/status
  - natmeta/status
  - nats/status
  - sitemeta/status
  - sites/status
  - softgatemeta/status
  - softgates/status
  - subnetmeta/status
  - subnets/status
  - switches/status
  - switchmeta/status
  - vnetmeta/status
  - vnets/status
  verbs:
  - get
  - patch
  - update
