# permissions for end users to edit softgatemeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: softgatemeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - softgatemeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - softgatemeta/status
  verbs:
  - get
