# permissions for end users to view softgatemeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: softgatemeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - softgatemeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - softgatemeta/status
  verbs:
  - get
