# permissions for end users to edit subnetmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnetmeta-editor-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - subnetmeta
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - subnetmeta/status
  verbs:
  - get
