# permissions for end users to view subnetmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnetmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - subnetmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - subnetmeta/status
  verbs:
  - get
