# permissions for end users to view vnetmeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vnetmeta-viewer-role
rules:
- apiGroups:
  - k8s.netris.ai
  resources:
  - vnetmeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.netris.ai
  resources:
  - vnetmeta/status
  verbs:
  - get
