apiVersion: k8s.netris.ai/v1alpha1
kind: BGP
metadata:
  name: artash-kube-test
spec:
  site: Artash
  hardware: terraform-sg
  neighborAs: 2345656
  transport:
    type: port
    name: swp37@artash-spine-1
  multihop:
    neighborAddress: 8.8.8.8
  localIP: 99.0.5.1/24
  remoteIP: 99.0.5.2/24
  description: K8S
  state: enabled
