apiVersion: k8s.netris.ai/v1alpha1
kind: BGP
metadata:
  name: artash-test 
spec:
  site: Yerevan
  softgate: sg01
  neighborAs: 23456
  transport:
    type: port
    name: swp13@yerevan-spine2
  localIP: 1.0.32.11/24
  remoteIP: 1.0.32.12/24
  description: K8S
  state: enabled
  terminateOnSwitch:
    enabled: false
    switchName: spine1
