apiVersion: k8s.netris.ai/v1alpha1
kind: BGP
metadata:
  name: artash-kube-test
spec:
  site: Artash
  hardware: auto
  neighborAs: 23456
  transport:
    type: vnet
    name: artash-kube
  multihop:
    neighborAddress: 8.8.8.8
  localIP: 99.0.4.1/24
  remoteIP: 99.0.4.2/24
  description: K8S
  state: enabled
