apiVersion: k8s.netris.ai/v1alpha1
kind: InventoryProfile
metadata:
  name: my-profile
spec:
  description: My First Inventory Profile
  timezone: America/Los_Angeles
  allowSshFromIpv4:
    - 100.71.56.0/24
    - 203.0.113.0/24
  allowSshFromIpv6:
    - 2001:db8:acad::/64
  ntpServers:
    - 0.pool.ntp.org
    - 132.163.96.5
  dnsServers:
    - 1.1.1.1
    - 8.8.8.8
  customRules:
    - srcSubnet: 10.0.0.0/8
      # srcPort: ""
      dstPort: "8443"
      protocol: tcp
