apiVersion: k8s.netris.ai/v1alpha1
kind: L4LB
metadata:
  name: my-l4lb
spec:
  ownerTenant: Admin
  site: santa-clara
  state: active
  protocol: tcp
  frontend:
    port: 31434
    # ip: 203.0.113.150
  backend:
    - 203.0.113.50:443
    - 203.0.113.51:443
  check:
    type: http
    timeout: 3000
    requestPath: /
