apiVersion: k8s.netris.ai/v1alpha1
kind: L4LB
metadata:
  name: artash-test
spec:
  ownerTenant: qa-tenant
  site: Yerevan
  state: active
  protocol: tcp
  frontend:
    port: 456
    ip: 5.0.32.2
  backend:
    - 5.0.32.5:23456
  check:
    type: http
    timeout: 3000
    requestPath: /
