apiVersion: k8s.netris.ai/v1alpha1
kind: L4LB
metadata:
  name: my-l4lb
spec:
  ownerTenant: Admin
  site: santa-clara
  vpc: prod-vpc
  state: active
  protocol: tcp
  frontend:
    port: 8443
    ip: 203.0.113.150
  backend:
    - 100.71.56.100:443
    - 100.71.56.101:443
  check:
    type: http
    timeout: 3000
    requestPath: /
