apiVersion: k8s.netris.ai/v1alpha1
kind: VNet
metadata:
  name: my-vnet
spec:
  vlanId: "auto"
  ownerTenant: Admin
  guestTenants: []
  sites:
    - name: santa-clara
      gateways:
        - prefix: 172.25.25.5/24
          dhcp: enabled
          dhcpOptionSet: Default
          dhcpStartIP: 172.25.25.6
          dhcpEndIP: 172.25.25.254
      switchPorts:
        - name: swp5@my-sw01
          vlanId: 1050
        - name: swp7@my-sw02