apiVersion: k8s.netris.ai/v1alpha1
kind: VNet
metadata:
  name: artash-test
spec:
  ownerTenant: Admin
  guestTenants: []
  sites:
    - name: Yerevan
      gateways:
        - 2.0.0.9/18
      switchPorts:
        - name: swp16@yerevan-leaf1
          vlanId: 2000
