apiVersion: k8s.netris.ai/v1alpha1
kind: VNet
metadata:
  name: my-vnet
spec:
  ownerTenant: Admin
  guestTenants: []
  sites:
    - name: santa-clara
      gateways:
        - 203.0.113.1/25
        - 2001:db8:acad::fffe/64
      switchPorts:
        - name: swp5@my-sw01
          vlanId: 1050
        - name: swp7@my-sw02
