apiVersion: k8s.netris.ai/v1alpha1
kind: VNet
metadata:
  name: myvnet
spec:
  ownerTenant: Admin
  guestTenants: []
  sites:
    - name: Yerevan
      gateways:
        - 109.23.0.6/24
        - 2001:db8:acad::fffe/64
      switchPorts:
        - name: swp5@rlab-spine1
          vlanId: 1050
        - name: swp7@rlab-leaf1
