# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/k8s.netris.ai_vnets.yaml
- bases/k8s.netris.ai_vnetmeta.yaml
- bases/k8s.netris.ai_bgps.yaml
- bases/k8s.netris.ai_bgpmeta.yaml
- bases/k8s.netris.ai_l4lbs.yaml
- bases/k8s.netris.ai_l4lbmeta.yaml
- bases/k8s.netris.ai_sites.yaml
- bases/k8s.netris.ai_sitemeta.yaml
- bases/k8s.netris.ai_allocations.yaml
- bases/k8s.netris.ai_allocationmeta.yaml
- bases/k8s.netris.ai_subnets.yaml
- bases/k8s.netris.ai_subnetmeta.yaml
- bases/k8s.netris.ai_softgates.yaml
- bases/k8s.netris.ai_softgatemeta.yaml
- bases/k8s.netris.ai_switches.yaml
- bases/k8s.netris.ai_switchmeta.yaml
- bases/k8s.netris.ai_controllers.yaml
- bases/k8s.netris.ai_controllermeta.yaml
- bases/k8s.netris.ai_links.yaml
- bases/k8s.netris.ai_linkmeta.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_vnets.yaml
#- patches/webhook_in_vnetmeta.yaml
#- patches/webhook_in_bgps.yaml
#- patches/webhook_in_bgpmeta.yaml
#- patches/webhook_in_l4lbs.yaml
#- patches/webhook_in_l4lbmeta.yaml
#- patches/webhook_in_sites.yaml
#- patches/webhook_in_sitemeta.yaml
#- patches/webhook_in_allocations.yaml
#- patches/webhook_in_allocationmeta.yaml
#- patches/webhook_in_subnets.yaml
#- patches/webhook_in_subnetmeta.yaml
#- patches/webhook_in_softgates.yaml
#- patches/webhook_in_softgatemeta.yaml
#- patches/webhook_in_switches.yaml
#- patches/webhook_in_switchmeta.yaml
#- patches/webhook_in_controllers.yaml
#- patches/webhook_in_controllermeta.yaml
#- patches/webhook_in_links.yaml
#- patches/webhook_in_linkmeta.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_vnets.yaml
#- patches/cainjection_in_vnetmeta.yaml
#- patches/cainjection_in_bgps.yaml
#- patches/cainjection_in_bgpmeta.yaml
#- patches/cainjection_in_l4lbs.yaml
#- patches/cainjection_in_l4lbmeta.yaml
#- patches/cainjection_in_sites.yaml
#- patches/cainjection_in_sitemeta.yaml
#- patches/cainjection_in_allocations.yaml
#- patches/cainjection_in_allocationmeta.yaml
#- patches/cainjection_in_subnets.yaml
#- patches/cainjection_in_subnetmeta.yaml
#- patches/cainjection_in_softgates.yaml
#- patches/cainjection_in_softgatemeta.yaml
#- patches/cainjection_in_switches.yaml
#- patches/cainjection_in_switchmeta.yaml
#- patches/cainjection_in_controllers.yaml
#- patches/cainjection_in_controllermeta.yaml
#- patches/cainjection_in_links.yaml
#- patches/cainjection_in_linkmeta.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
