name: Create issue on commit
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Switch the default system shell
      run: |
        ls -al /bin/sh
        rm /bin/sh
        ln -s bash /bin/sh
        ls -al /bin/sh

    - name: make test
      run: make test
